--Começando PL/SQL

--Primeiros Programas
set serveroutput on;

DECLARE
    v_ID NUMBER(5):= 1;
BEGIN 
    dbms_output.put_line(v_ID);
    v_ID := 2;
    dbms_output.put_line(v_ID);
END;

--Comandos SQL no PL/SQL

DECLARE
   v_ID NUMBER(5) :=1;
     v_DESCRICAO VARCHAR2(100) := 'Varejo';
BEGIN
   INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (v_ID, v_DESCRICAO); 
   COMMIT; --Precisa do COMMIT para confirmar a alteração

END;

DECLARE
   v_ID SEGMERCADO.ID%type :=4;
     v_DESCRICAO SEGMERCADO.DESCRICAO%TYPE := 'Atacado';
BEGIN
   INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (v_ID, v_DESCRICAO); 
     COMMIT;

END;

DECLARE
   v_ID SEGMERCADO.ID%type :=3;
     v_DESCRICAO SEGMERCADO.DESCRICAO%TYPE := 'Atacadista';
BEGIN
    UPDATE SEGMERCADO SET DESCRICAO = UPPER(v_DESCRICAO) WHERE ID = v_ID;
    
    v_ID :=1;
    v_DESCRICAO := 'Varejista';
    UPDATE SEGMERCADO SET DESCRICAO = UPPER(v_DESCRICAO) WHERE ID = v_ID;
    
    v_ID :=2;
    v_DESCRICAO := 'Industrial';
    UPDATE SEGMERCADO SET DESCRICAO = UPPER(v_DESCRICAO) WHERE ID = v_ID;
    
     COMMIT;
END;

DECLARE
   v_ID SEGMERCADO.ID%type := 5;
   v_DESCRICAO SEGMERCADO.DESCRICAO%type := 'Esportistas';
BEGIN

INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (v_ID, UPPER(v_DESCRICAO));
   COMMIT;
END;

DECLARE
   v_ID SEGMERCADO.ID%type := 4;
BEGIN

DELETE FROM SEGMERCADO WHERE ID = v_ID; 
   COMMIT;
END;

--Criando Procedures e Funções

Create OR REPLACE PROCEDURE incluir_segmercado
(p_ID IN SEGMERCADO.ID%type, p_DESCRICAO IN SEGMERCADO.DESCRICAO%type)

IS

BEGIN
    INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (p_ID, UPPER(p_DESCRICAO));
    COMMIT;
END;

--EXECUTE
EXECUTE incluir_segmercado(4,'Farmaceuticos');

Create OR REPLACE PROCEDURE incluir_segmercado2
(p_ID IN SEGMERCADO.ID%type, p_DESCRICAO IN SEGMERCADO.DESCRICAO%type)

IS

BEGIN
    INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (p_ID, UPPER(p_DESCRICAO));
    COMMIT;
END;

Create OR REPLACE PROCEDURE incluir_segmercado3
(p_ID IN SEGMERCADO.ID%type, p_DESCRICAO IN SEGMERCADO.DESCRICAO%type)

IS

BEGIN
    INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (p_ID, UPPER(p_DESCRICAO));
    COMMIT;
END;


SET SERVEROUTPUT ON;

DECLARE
    v_ID SEGMERCADO.ID%type := 2;
    v_DESCRICAO SEGMERCADO.DESCRICAO%type;
BEGIN
    SELECT DESCRICAO INTO v_DESCRICAO FROM SEGMERCADO WHERE ID = v_ID;
    dbms_output.put_line(v_DESCRICAO);
END;

--Criando uma função 

CREATE OR REPLACE FUNCTION obter_descricao_segmercado
(p_ID IN SEGMERCADO.ID%type)

RETURN SEGMERCADO.DESCRICAO%type

IS
    v_DESCRICAO SEGMERCADO.DESCRICAO%type;
BEGIN
    SELECT DESCRICAO INTO v_DESCRICAO FROM SEGMERCADO WHERE ID = p_ID;
    RETURN v_DESCRICAO;
END;

SELECT ID,obter_descricao_segmercado(ID), DESCRICAO, LOWER(DESCRICAO) FROM SEGMERCADO WHERE ID=1;

VARIABLE g_DESCRICAO VARCHAR2(100);
EXECUTE :g_DESCRICAO:=obter_descricao_segmercado(3);
PRINT g_DESCRICAO;


SET SERVEROUTPUT ON;

DECLARE
    v_DESCRICAO SEGMERCADO.DESCRICAO%type;
    v_ID SEGMERCADO.ID%type := 1;
BEGIN
    v_DESCRICAO := obter_descricao_segmercado(v_ID);
    dbms_output.put_line('A descrição do segmento de mercado é: ' || v_DESCRICAO);
END;


CREATE OR REPLACE PROCEDURE incluir_cliente
(
p_ID CLIENTE2.ID%type,
p_RAZAO CLIENTE2.RAZAO_SOCIAL%type,
p_CNPJ CLIENTE2.CNPJ%type,
p_SEGMERCADO CLIENTE2.SEGMERCADO_ID%type,
p_FATURAMENTO CLIENTE2.FATURAMENTO_PREVISTO%type,
p_CATEGORIA CLIENTE2.CATEGORIA%type
)
IS
BEGIN
    INSERT INTO CLIENTE2
    VALUES
    (p_ID, p_RAZAO, p_CNPJ, p_SEGMERCADO, SYSDATE, p_FATURAMENTO, p_CATEGORIA);
    COMMIT;
END;

EXECUTE incluir_cliente (1, 'SUPERMERCADOS CAMPEAO', '1234567890', 1, 90000, 'MEDIO GRANDE');











